ALTER TABLE users
ADD COLUMN IF NOT EXISTS username VARCHAR(50),
ADD COLUMN IF NOT EXISTS selected_title VARCHAR(100) DEFAULT 'New Member',
ADD COLUMN IF NOT EXISTS unlocked_titles TEXT[] DEFAULT ARRAY['New Member']; 